In [36]:
import pandas as pd
df=pd.read_csv("IRIS.csv")
df2=df.copy()

print(df2.head(10))

print(df2.shape,type(df2))

print(df2.describe())

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa
5           5.4          3.9           1.7          0.4  Iris-setosa
6           4.6          3.4           1.4          0.3  Iris-setosa
7           5.0          3.4           1.5          0.2  Iris-setosa
8           4.4          2.9           1.4          0.2  Iris-setosa
9           4.9          3.1           1.5          0.1  Iris-setosa
(150, 5) <class 'pandas.core.frame.DataFrame'>
       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [44]:
#df2=df2[df2["petal_length"]>4.5 and df["species"]=="Iris-virginica"]
# the above code gives error becuase firstly ans works with series 1d only
# and [] these brackets wont work except 1 d data we also need ()
new1=df2[df2["petal_length"]>4.5]
# this works fine since one condition is there 
new=df2[(df2["petal_length"]>4.5) & (df2["species"]=="Iris-virginica")]

In [45]:
df.groupby("species")["sepal_length"].mean()

species
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: sepal_length, dtype: float64

In [51]:
df.groupby("species").aggregate(
    avg_sepal_lenght=("sepal_length","mean"),
    Maximum_petal_width=("petal_width","max"),
    Standard_deviation_of_sepal_width=("sepal_width","std")
)

,avg_sepal_lenght,Maximum_petal_width,Standard_deviation_of_sepal_width
species,,,
Iris-setosa,5.006,0.6,0.381024
Iris-versicolor,5.936,1.8,0.313798
Iris-virginica,6.588,2.5,0.322497

In [57]:
df["petal_ratio"] = df["petal_length"] / df["petal_width"]
df=df.assign(petal_ratio=df["petal_length"]/df["petal_width"])
df.groupby("species")["petal_ratio"].mean()

species
Iris-virginica    2.783389
Name: petal_ratio, dtype: float64

In [63]:
df=pd.read_csv("Titanic-Dataset.csv")
df2=df[["Name", "Sex", "Age","Fare","Survived"]]
df2

,Name,Sex,Age,Fare,Survived
0,"Braund, Mr. Owen Harris",male,22.0,7.2500,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1
2,"Heikkinen, Miss. Laina",female,26.0,7.9250,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1
4,"Allen, Mr. William Henry",male,35.0,8.0500,0
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,27.0,13.0000,0
887,"Graham, Miss. Margaret Edith",female,19.0,30.0000,1
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,23.4500,0
889,"Behr, Mr. Karl Howell",male,26.0,30.0000,1
890,"Dooley, Mr. Patrick",male,32.0,7.7500,0

In [68]:
data=df2[(df2["Sex"]=="female") & (df2["Fare"]>30)]
data

,Name,Sex,Age,Fare,Survived
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1
9,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,30.0708,1
25,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,31.3875,1
31,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,146.5208,1
...,...,...,...,...,...
853,"Lines, Miss. Mary Conover",female,16.0,39.4000,1
856,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,164.8667,1
863,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,69.5500,0
871,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,52.5542,1
879,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,83.1583,1

In [70]:
df.groupby("Pclass").agg(
    Survival_rate=("Survived","mean"),
    Average_Fare=("Fare","mean"),
    Average_age=("Age","mean")
)

        Survival_rate  Average_Fare  Average_age
Pclass
1            0.629630     84.154687    38.233441
2            0.472826     20.662183    29.877630
3            0.242363     13.675550    25.140620